[[$head?&classex=`articles`&articles=`1`]]
<section class="section4">
    <h2>[[*pagetitle]]</h2>
    <div class="section-wrap">
        <div class="container">
            <!--<div class="events block-left">
                <div class="scroll no-bar">
                    <div class="scroll-inner">
                        <div class="block">
                            <div class="top">
                                <h6>Пошук спеціальностей</h6>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Випускникам 11 класів</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <div class="list sub-list list-top">
                                    <a href="#" class="link_list ">
                                        <span>ЗНО - 2017</span>
                                        <div class="triangle-right"></div>
                                    </a>
                                    <ul class="ul-border list-zno-ul-none">
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Вартість навчання 2017-2018
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Конкурсні предмети
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                    </ul>
                                </div>
                                <div class="list sub-list">
                                    <a href="#" class="link_list  "><span>Вступна кампанія</span>
                                        <div class="triangle-right"></div>
                                    </a>
                                    <ul class="ul-border list-zno-ul-none">
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Вартість навчання 2017-2018
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Конкурсні предмети
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                    </ul>
                                </div>
                                <div class="list sub-list">
                                    <a href="#" class="link_list  "><span>Порядоку подачі документів</span>
                                        <div class="triangle-right"></div>
                                    </a>
                                    <ul class="ul-border list-zno-ul-none">
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Вартість навчання 2017-2018
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Конкурсні предмети
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                    </ul>
                                </div>
                                <div class="list sub-list">
                                    <a href="#" class="link_list  "><span>Терміни зарахування</span>
                                        <div class="triangle-right"></div>
                                    </a>
                                    <ul class="ul-border list-zno-ul-none">
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Вартість навчання 2017-2018
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Конкурсні предмети
                                        </li>
                                        <li>
                                            <img src="assets/images/artur/dot-blue.png" class="dot-blue-li" alt="">
                                            Перелік спеціальностей
                                        </li>
                                    </ul>
                                </div>
                                <div class="list">
                                    <a href="#" class="link_list  sub-list">
                                        <div class="triangle_arrow_right"></div>
                                        <span class="link_list_span">Творчий конкурс</span>
                                    </a>
                                    <ul></ul>
                                </div>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Вступнику на старші курси</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>International Students</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Друга вища освіта</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Аспірантура та Докторантура</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Конкурс та зарахування</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Правила та обсяги прийому</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                                <a href="" class="announc-more">читати далi</a>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Приймальна комісія</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Підготовка до вступу</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Корисна інформація</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                        <div class="block">
                            <div class="top">
                                <h6>Важливі повідомлення</h6>
                                <i></i>
                            </div>
                            <div class="text">
                                <p>З 22.03.2017 у рамках програми по удосконаленню комунікативних і мовленнєвих
                                    навичок з англійської мови.Кафедра ділової іноземної мови та міжнародної
                                    комунікації продовжує проводити “English Speaking Clube” кожну середу ( по
                                    парному тижню) 3 пара (11:20-12:40) аудиторія 309</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>-->
            <div class="content block-center">
                <nav class="fall-down-main-menu clear">
                    <ul class="content-button type_list js-tabs-list">
                        [[!pdoResources?
                        &parents=`37`
                        &depth=`0`
                        &resources=``
                        &showLog=`0`
                        &sortby=`menuindex`
                        &sortdir=`ASC`
                        &showHidden=`1`
                        &context=`[[*context_key]]`
                        &tpl=`@INLINE
                        <li class="content-button-li ">[[+pagetitle]]</li>
                        `
                        ]]
                    </ul>
                    <ul class="table_category category_list">
                        <a href="#" class="fall-down-click drop-down-init">
                            <span>КАТЕГОРІЯ</span>
                            <div class="triangle-down-nav"></div>
                        </a>
                        <ul class="fall-down-li drop-down">
                            <li>УНІВЕРСИТЕТ</li>
                            <li>ОСВІТА</li>
                            <li>ДОЗВІЛЛЯ</li>
                            <li>НАУКА</li>
                            <li>СПОРТ</li>
                        </ul>
                    </ul>
                </nav>
                <div class="tabs">
                    <div class="tab">
                        <div class="announcements-wrap">
                            <div class="announce-list">
                                [[!pdoResources?
                                &parents=`39`
                                &tvPrefix=``
                                &includeTVs=`article_date`
                                &includeContent=`1`
                                &where=``
                                &showLog=`0`
                                &showHidden=`1`
                                &context=`[[*context_key]]`
                                &tpl=`announce-item-tpl`
                                ]]
                            </div>
                        </div>
                        <div class="custom-place">
                            <div class="slider-nav">
                                <i class="icon-arrow-left" style="display: inline;"></i>
                                <ul class="slick-dots" style="display: block;" role="tablist">
                                    <li class="slick-active">
                                        <button type="button" data-role="none" role="button" tabindex="0">1</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">2</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">3</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">4</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">5</button>
                                    </li>
                                </ul>
                                <i class="icon-arrow-right" style="display: inline;"></i>
                            </div>
                        </div>
                    </div>
                    <div class="tab">
                        <div class="articles-all">
                            [[!pdoResources?
                            &parents=`38`
                            &tvPrefix=``
                            &includeTVs=`article_date`
                            &includeContent=`1`
                            &where=``
                            &showLog=`0`
                            &showHidden=`1`
                            &context=`[[*context_key]]`
                            &tpl=`announce-item-tpl`
                            ]]
                        </div>
                        <div class="custom-place">
                            <div class="slider-nav">
                                <i class="icon-arrow-left" style="display: inline;"></i>
                                <ul class="slick-dots" style="display: block;" role="tablist">
                                    <li class="slick-active">
                                        <button type="button" data-role="none" role="button" tabindex="0">1</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">2</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">3</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">4</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">5</button>
                                    </li>
                                </ul>
                                <i class="icon-arrow-right" style="display: inline;"></i>
                            </div>
                        </div>
                    </div>
                    <div class="tab">
                        <div class="articles-all">
                            [[!pdoResources?
                            &parents=`83`
                            &tvPrefix=``
                            &includeTVs=`img_main,article_date`
                            &includeContent=`1`
                            &showHidden=`1`
                            &context=`[[*context_key]]`
                            &tpl=`articles-item-tpl`
                            &showLog=`0`
                            ]]
                        </div>
                        <div class="custom-place">
                            <div class="slider-nav">
                                <i class="icon-arrow-left" style="display: inline;"></i>
                                <ul class="slick-dots" style="display: block;" role="tablist">
                                    <li class="slick-active">
                                        <button type="button" data-role="none" role="button" tabindex="0">1</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">2</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">3</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">4</button>
                                    </li>
                                    <li>
                                        <button type="button" data-role="none" role="button" tabindex="0">5</button>
                                    </li>
                                </ul>
                                <i class="icon-arrow-right" style="display: inline;"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--footer-->
[[$foot?&articles=`1`]]
