[[$head?&classex=`vstupnik`&vstup=`1`]]

<section class="section1">
    <div class="container">
        <!--<div class="breadcrumbs">
            <li><a href="">Головна</a></li>
            <li><a href="">Вступнику</a></li>
        </div>-->
        <div class="title">
            <h1>[[*vstup_title_sec01]]</h1>
        </div>
    </div>
    <div class="section-wrap">
        <div class="slider slider-main chocolate-slider simple-silk customPagin new with-container">
            [[!getImageList?
            &docid=`[[*id]]`
            &tvname=`migx-vstup-section-01`
            &tpl=`@CODE:
            <div class="slide inner">
                <div class="image chocolate-image-move">
                    <img src="[[+image]]" alt="[[+alt]]" title="[[+img_title]]">
                </div>
            </div>
            `
            ]]
        </div>
        <div class="mouse-scroll">
            <div class="mouse-wrapp">
                <div class="mouse"></div>
            </div>
        </div>
    </div>
</section><!--section1-->
<section class="section2">
    <div class="section-wrap">
        <div class="container">
            <div class="inform-b-wrap">
                [[pdoResources?
                &parents=`45`
                &tpl=`inform-sec-02-item`
                &sortby=`menuindex`
                &sortdir=`ASC`
                &limit=`0`
                &includeContent=`1`
                &includeTVs=`vstup_bg,vstup_icon`
                &tvPrefix=``
                &where=`{"template:!=":10}`
                &showLog=`0`
                &context=`[[*context_key]]`
                ]]
            </div>
        </div>
    </div>
</section><!--section2-->
<section class="section3">
    <div class="section-wrap">
        <div class="vertical-wrap">
            <div class="vertical-lines-subtitle lines-subtitle">
                <div class="h2">[[*vstup_title_sec03]]</div>
                <div class="cutter">
                    <div><span><i>[[*vstup_title_sec03]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec03]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec03]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec03]]</i></span></div>
                </div>
            </div>
        </div>
        <div class="container">
            <h2>[[*vstup_subtitle_sec03]]</h2>
            <div class="why-b">
                [[!getImageList?
                &docid=`[[*id]]`
                &tvname=`migx-vstup-why-collection`
                &tpl=`vstup-why-item`
                ]]
            </div>
        </div>
    </div>
</section><!--section3-->
<section class="section4 grey-section">
    <div class="section-wrap">
        <div class="container">
            <div class="banner">
                <img src="[[*vstup-baner-sec-04-image]]"
                     alt="[[*vstup-baner-sec-04-title]]">
                <div class="banner-text">[[*vstup-baner-sec-04-title]]</div>
                <form action="" class="form-vipusk">
                    <input type="text" name="name" placeholder="ПІБ">
                    <input type="text" name="email" placeholder="E-mail">
                    <input type="text" name="tel" placeholder="+380931234567">
                    <button class="button">Вступна компанія</button>
                </form>
            </div>
        </div>
    </div>
</section><!--section4-->
<section class="section5">
    <div class="section-wrap">
        <div class="vertical-lines">
            <div class="vertical-wrap">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
        <div class="vertical-wrap">
            <div class="vertical-lines-subtitle lines-subtitle">
                <div class="h2">[[*vstup_title_sec05]]</div>
                <div class="cutter">
                    <div><span><i>[[*vstup_title_sec05]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec05]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec05]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec05]]</i></span></div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="sec-head">
                <h2>[[*vstup_subtitle_sec05]]</h2>
            </div>
            <div class="komfort">
                <div class="komfort-slider-wrap">
                    <div class="slider komfort-slider simple-silk customPagin chocolate-slider nav-for">
                        [[!getImageList?
                        &docid=`[[*id]]`
                        &tvname=`migx-komfort-social_behavior-slider`
                        &tpl=`@CODE:
                        <div class="inner slide">
                            <div class="img-wrap chocolate-image-move">
                                <img src="[[+image]]" alt="[[+alt]]"
                                     title="[[+img_title]]">
                                <div class="hover-this"></div>
                            </div>
                            <div class="moveto"
                                 data-to=".slider.nav-from.no-nav.komfort-text"
                                 data-parent=".komfort-slider-wrap">
                                <div class="text">[[+title]]
                                    <div>
                                        <hr class="small-line">
                                    </div>
                                </div>
                            </div>
                        </div>
                        `
                        ]]
                    </div>
                    <div class="slider nav-from no-nav komfort-text">
                    </div>
                </div><!--social_behavior-->
                <div class="komfort-slider-wrap">
                    <div class="slider komfort-slider simple-silk customPagin chocolate-slider nav-for">
                        [[!getImageList?
                        &docid=`[[*id]]`
                        &tvname=`migx-komfort-sport_komplex-slider`
                        &tpl=`@CODE:
                        <div class="inner slide">
                            <div class="img-wrap chocolate-image-move">
                                <img src="[[+image]]" alt="[[+alt]]"
                                     title="[[+img_title]]">
                                <div class="hover-this"></div>
                            </div>
                            <div class="moveto"
                                 data-to=".slider.nav-from.no-nav.komfort-text"
                                 data-parent=".komfort-slider-wrap">
                                <div class="text">[[+title]]
                                    <div>
                                        <hr class="small-line">
                                    </div>
                                </div>
                            </div>
                        </div>
                        `
                        ]]
                    </div>
                    <div class="slider nav-from no-nav komfort-text">
                    </div>
                </div><!--sport_komplex-->
                <div class="komfort-slider-wrap">
                    <div class="slider komfort-slider simple-silk customPagin chocolate-slider nav-for">
                        [[!getImageList?
                        &docid=`[[*id]]`
                        &tvname=`migx-komfort-canteen-slider`
                        &tpl=`@CODE:
                        <div class="inner slide">
                            <div class="img-wrap chocolate-image-move">
                                <img src="[[+image]]" alt="[[+alt]]"
                                     title="[[+img_title]]">
                                <div class="hover-this"></div>
                            </div>
                            <div class="moveto"
                                 data-to=".slider.nav-from.no-nav.komfort-text"
                                 data-parent=".komfort-slider-wrap">
                                <div class="text">[[+title]]
                                    <div>
                                        <hr class="small-line">
                                    </div>
                                </div>
                                <div>
                        </div>
                        `
                        ]]
                            </div>
                            <div class="slider nav-from no-nav komfort-text">
                            </div>
                </div><!--canteen-->
            </div>
        </div>
    </div>
</section><!--section5-->
<section class="section6 grey-section">
    <div class="section-wrap">
        <div class="sec-head">
            <div class="vertical-wrap">
                <div class="horizontal-lines-subtitle lines-subtitle">
                    <div class="h2">[[*vstup_title_sec06]]</div>
                    <div class="cutter">
                        <div><span><i>[[*vstup_title_sec06]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec06]]</i></span></div>
                    </div>
                </div>
            </div>
            <div class="container">
                <h2>[[*vstup_subtitle_sec06]]</h2>
            </div>
        </div>
        <div class="container">
            <div class="teachers-wrap">
                <div class="slider teachers-slider simple-silk no-nav chocolate-slider nav-from">
                    [[pdoResources?
                    &parents=`67`
                    &includeContent=`1`
                    &includeTVs=`teachers_avatar,teachers_name,teachers_position,teachers_about,teachers_twitter,teachers_facebook`
                    &tvPrefix=``
                    &showLog=`0`
                    &showHidden=`1`
                    &context=`[[*context_key]]`
                    &tpl=`teachers-slider-image-item`
                    ]]
                </div>
                <div class="slider slider-text-teacher customPagin pagin-custom-place nav-for">
                </div>
                <div class="custom-place"></div>
            </div>
        </div>
    </div>
</section><!--section6-->
<section class="section7">
    <div class="section-wrap">
        <div class="vertical-lines">
            <div class="vertical-wrap">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
        <div class="sec-head">
            <div class="vertical-wrap">
                <div class="vertical-lines-subtitle lines-subtitle">
                    <div class="h2">[[*vstup_title_sec07]]</div>
                    <div class="cutter">
                        <div><span><i>[[*vstup_title_sec07]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec07]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec07]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec07]]</i></span></div>
                    </div>
                </div>
            </div>
            <div class="container">
                <h2>[[*vstup_subtitle_sec07]]</h2>
            </div>
            <div class="dozvillya-wrap">
                <div class="doz doz_1">
                    <img src="assets/images/vstup/doz1.jpg" alt="">
                    <div class="doz-text-bl doz-init-text">
                        <div><span>САМОВРЯДУВАННЯ</span></div>
                    </div>
                    <div class="doz-text-bl doz-hover-text">
                        <ul>
                            <li><a href="">Клуб КВН</a></li>
                            <li><a href="">Танцювальний гурток</a></li>
                            <li><a href="">Науковий гурток</a></li>
                            <li><a href="">Музична група</a></li>
                            <li><a href="">Літературний клуб</a></li>
                        </ul>
                    </div>
                </div>
                <div class="doz doz_2">
                    <img src="assets/images/vstup/doz2.jpg" alt="">
                    <div class="doz-text-bl doz-init-text">
                        <div><span>ВИСТАВИ ТА КОНКУРСИ</span></div>
                    </div>
                    <div class="doz-text-bl doz-hover-text">
                        <ul>
                            <li><a href="">Клуб КВН</a></li>
                            <li><a href="">Танцювальний гурток</a></li>
                            <li><a href="">Науковий гурток</a></li>
                            <li><a href="">Музична група</a></li>
                            <li><a href="">Літературний клуб</a></li>
                        </ul>
                    </div>
                </div>
                <div class="doz doz_3">
                    <img src="assets/images/vstup/doz3.jpg" alt="">
                    <div class="doz-text-bl doz-init-text">
                        <div><span>ВИСТАВИ ТА КОНКУРСИ</span></div>
                    </div>
                    <div class="doz-text-bl doz-hover-text">
                        <ul>
                            <li><a href="">Клуб КВН</a></li>
                            <li><a href="">Танцювальний гурток</a></li>
                            <li><a href="">Науковий гурток</a></li>
                            <li><a href="">Музична група</a></li>
                            <li><a href="">Літературний клуб</a></li>
                        </ul>
                    </div>
                </div>
                <div class="doz doz_4">
                    <img src="assets/images/vstup/doz4.jpg" alt="">
                    <div class="doz-text-bl doz-init-text">
                        <div>
                            <span>СТУДЕНТСЬКІ ВЕЧІРКИ</span></div>
                    </div>
                    <div class="doz-text-bl doz-hover-text">
                        <ul>
                            <li><a href="">Клуб КВН</a></li>
                            <li><a href="">Танцювальний гурток</a></li>
                            <li><a href="">Науковий гурток</a></li>
                            <li><a href="">Музична група</a></li>
                            <li><a href="">Літературний клуб</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!--section7-->
<section class="section8">
    <div class="section-wrap">
        <div class="vertical-lines">
            <div class="vertical-wrap">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
        <div class="sec-head">
            <div class="vertical-wrap">
                <div class="vertical-lines-subtitle when-grey lines-subtitle">
                    <div class="h2">[[*vstup_title_sec08]]</div>
                    <div class="cutter">
                        <div><span><i>[[*vstup_title_sec08]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec08]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec08]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec08]]</i></span></div>
                    </div>
                </div>
            </div>
            <div class="container">
                <h2>[[*vstup_subtitle_sec08]]</h2>
                <div class="slider-fakt-wrap">
                    <div class="slider-fakt-image slider not-fade-slider centerSlide  nav-for customPagin pagin-custom-place"
                         data-slides="5">
                        [[!getImageList?
                        &docid=`[[*id]]`
                        &tvname=`migx-vstup-fakt-slider`
                        &tpl=`vstup-fakt-slider-item`
                        ]]
                    </div>
                    <div class="clear"></div>
                    <div class="slider student-info no-nav nav-from"></div>
                    <div class="clear"></div>
                    <div class="custom-place"></div>
                </div>
            </div>
        </div>
    </div>
</section><!--section8-->
<!--graduates work in-->
<section class="section10 work grey-section">
    <div class="section-wrap">
        <div class="vertical-wrap">
            <div class="vertical-lines-subtitle when-grey  lines-subtitle">
                <div class="h2">[[*vstup_title_sec10]]</div>
                <div class="cutter">
                    <div><span><i>[[*vstup_title_sec10]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec10]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec10]]</i></span></div>
                    <div><span><i>[[*vstup_title_sec10]]</i></span></div>
                </div>
            </div>
        </div>
        <div class="container">
            <h2 class="work-head">[[*vstup_subtitle_sec10]]</h2>
        </div>

        <div class="work-links">
            [[!getImageList?
            &docid=`[[++site_start]]`
            &tvname=`migx-graduates-works`
            &tpl=`work-graduates-item`
            ]]
        </div>
    </div>
</section><!--section10-->
<!--an interesting-->
<section class="section11 interesting">
    <div class="section-wrap">
        <div class="vertical-lines">
            <div class="vertical-wrap">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
        <div class="sec-head">
            <div class="vertical-wrap">
                <div class="vertical-lines-subtitle when-grey lines-subtitle">
                    <div class="h2">[[*vstup_title_sec11]]</div>
                    <div class="cutter">
                        <div><span><i>[[*vstup_title_sec11]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec11]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec11]]</i></span></div>
                        <div><span><i>[[*vstup_title_sec11]]</i></span></div>
                    </div>
                </div>
            </div>
            <div class="container">
                <h2>[[*vstup_subtitle_sec11]]</h2>
            </div>
        </div>
        <div class="container">
            <div class="article-wrap">
                [[pdoResources?
                &parents=`65`
                &includeContent=`1`
                &includeTVs=`event_date`
                &tvPrefix=``
                &sortby=`event_date`
                &sortdir=`DESC`
                &showLog=`0`
                &showHidden=`1`
                &context=`[[*context_key]]`
                &limit=`4`
                &tpl=`vstup-vaghno-article-item`
                ]]
            </div>
            <a href="[[~[[%65:bid]]]]" class="button" tabindex="0">ВСІ
                ОГОЛОШЕННЯ</a>
        </div>
    </div>
</section><!--section11-->

[[$foot]]